apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-crud.fullname" . }}-changelog-config
  annotations:
    "helm.sh/hook": pre-install
data:
  changelog_app: |
    {{ .Values.migration.changelog.app | nindent 4 }}
  changelog_auth: |
    {{ .Values.migration.changelog.auth | nindent 4 }}
