apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.auth.name }}
  annotations:
    "helm.sh/hook": pre-install
data:
  auth.port: {{ .Values.auth.http.port | quote }}
  auth.db.generation: {{ .Values.auth.hibernate.generation }}
  auth.db.log: {{ .Values.auth.hibernate.log }}