apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "user-crud.fullname" . }}-db-auth-migration
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    metadata:
      name: db-auth-migration
    spec:
      initContainers:
        - name: init-db-check
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for PostgreSQL to be ready...";
              until nc -z {{ .Values.services.db_auth.name }} {{ .Values.services.db_auth.port }}; do
                echo "Database not ready yet, waiting...";
                sleep 5;
              done;
      containers:
        - name: db-auth-migration
          image: {{ include "user-crud.migration.image" . }}
          imagePullPolicy: Always
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.auth.name }}
                  key: auth_db_url
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.auth.name }}
                  key: auth_db_username
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.auth.name }}
                  key: auth_db_password
            - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
              value: {{ .Values.migration.volumeMount.mountPath }}
          volumeMounts:
            - name: {{ .Values.migration.volumeMount.name }}
              mountPath: {{ .Values.migration.volumeMount.rootPath }}{{ .Values.migration.volumeMount.mountPath }}
              subPath: changelog_auth
          command: [ "liquibase", "update", "--log-level=DEBUG" ]
      restartPolicy: OnFailure
      volumes:
        - name: {{ .Values.migration.volumeMount.name }}
          configMap:
            name: {{ include "user-crud.fullname" . }}-changelog-config