apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.auth.name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  auth_db_url: {{ include "user-crud.fullAuthUrl" . | b64enc }}
  auth_db_name: {{ .Values.db_auth.connection.name | b64enc }}
  auth_db_username: {{ .Values.db_auth.connection.username | b64enc }}
  auth_db_password: {{ .Values.db_auth.connection.password | b64enc }}