apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.application.name }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  db_url: {{ include "user-crud.fullUrl" . | b64enc }}
  db_name: {{ .Values.db_app.connection.name | b64enc }}
  db_username: {{ .Values.db_app.connection.username | b64enc }}
  db_password: {{ .Values.db_app.connection.password | b64enc }}
  exporter_db_data_source_name: {{ include "user-crud.fullUrlExporter" . | b64enc }}