apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "user-crud.fullname" . }}-ss-db
spec:
  serviceName: {{ .Values.services.db_app.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "user-crud.fullname" . }}-ss-db
  template:
    metadata:
      labels:
        app: {{ include "user-crud.fullname" . }}-ss-db
    spec:
      containers:
        - name: postgres
          image: {{ include "user-crud.db_app.image" . }}
          ports:
            - containerPort: {{ .Values.db_app.container.port }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.application.name }}
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.application.name }}
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.application.name }}
                  key: db_password
          volumeMounts:
            - name: {{ .Values.db_app.container.volumeMount.name }}
              mountPath: {{ .Values.db_app.container.volumeMount.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.db_app.container.volumeMount.name }}
      spec:
        accessModes: {{ .Values.db_app.container.volumeClaimTemplates.accessModes }}
        resources:
          requests:
            storage: {{ .Values.db_app.container.volumeClaimTemplates.resources.requests.storage }}
