apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.db_app.name }}
spec:
  selector:
    app: {{ include "user-crud.fullname" . }}-ss-db
  ports:
    - protocol: TCP
      port: {{ .Values.services.db_app.port }}
      targetPort: {{ .Values.db_app.container.port }}