apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.auth.name }}
spec:
  selector:
    app: {{ include "user-crud.fullname" . }}-auth
  ports:
    - protocol: TCP
      port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.auth.http.port }}