apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.application.name }}
  labels:
    {{- include "user-crud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.application.type }}
  ports:
    - name: web
      port: {{ .Values.services.application.port }}
      targetPort: {{ .Values.application.http.port }}
      protocol: TCP
  selector:
    {{- include "user-crud.selectorLabels" . | nindent 4 }}
