{
 "title": "Application User Service",
 "description": "Here are the metrics for the simple application, as well as the infrastructure metrics from k8s",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Percentiles for the application",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{job=\"user-crud-service-svc-app\"}[1m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket{job=\"user-crud-service-svc-app\"}[1m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{job=\"user-crud-service-svc-app\"}[1m])) by (le))",
     "legendFormat": "0.99"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"user-crud-service-svc-app\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Error Rate for the application",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"user-crud-service-svc-app\", status=~\"5..\"}[1m])) or vector(0)",
     "legendFormat": "error 5xx"
    }
   ]
  },
  {
   "title": "rps for the application",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"user-crud-service-svc-app\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Percentiles for the nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"m\"}[1m])) by (le))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"m\"}[1m])) by (le))",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"m\"}[1m])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Error Rate for the nginx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=\"m\", status=~\"5..\"}[1m])) or vector(0)",
     "legendFormat": "error 5xx"
    }
   ]
  },
  {
   "title": "rps for the nginx",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{namespace=\"m\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod!=\"\"}[1m])) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod!=\"\"}) by (pod)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}